services:
  traefik:
    image: traefik:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    security_opt:
      - no-new-privileges:true # helps to increase security
    secrets:
      - cf-token # the secret at the top of this file
    networks:
      - traefik_proxy
    ports:  # Traefik also support customized ports
      - 80:80
      - 443:443
    environment:
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - CF_API_EMAIL=${CF_API_EMAIL} # Cloudflare email
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf-token # see https://doc.traefik.io/traefik/https/acme/#providers
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ypei/libraries/docker/traefik/traefik.yml:/traefik.yml:ro
      - /home/ypei/libraries/docker/traefik/configs:/etc/traefik/configs:ro  # check .yaml or .yml per failure
      - /home/ypei/libraries/docker/traefik/acme.json:/acme.json
      - /home/ypei/libraries/docker/traefik/logs:/var/log/traefik
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.${CONTAINER_NAME}-secure.rule=Host(`traefik-internal.${DOMAIN}`)"
      - "traefik.http.routers.${CONTAINER_NAME}-secure.service=api@internal"
      - "traefik.http.routers.${CONTAINER_NAME}-secure.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.routers.${CONTAINER_NAME}-secure.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.${CONTAINER_NAME}-secure.tls.domains[0].sans=*.${DOMAIN}"

secrets:
  cf-token:
    file: ./cf-token

networks:
  traefik_proxy:
    external: true
