services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Los_Angeles
      - WEBUI_PORT=${WEBUI_PORT}
      - TORRENTING_PORT=${LISTEN_PORT}
    volumes:
      - ${LOCAL_PATH}/qbittorrent/config:/config
      - /mnt/external_drive/downloads/qb:/downloads
    ports:
      - ${WEBUI_PORT}:${WEBUI_PORT}
      - ${LISTEN_PORT}:${LISTEN_PORT}
      - ${LISTEN_PORT}:${LISTEN_PORT}/udp
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
